service: lambda-monolith

provider:
  name: aws
  region: sa-east-1
  stage: prod

useDotenv: true

package:
  patterns:
    - '!**/**'
    - dist/main.js

functions:
  main:
    handler: dist/main.handler
    name: lambda-monolith
    url: true
    runtime: nodejs20.x
    timeout: 15
    environment:
      NODE_ENV: prod
      DB_PASSWORD: ${env:DB_PASSWORD}
      DB_USERNAME: ${env:DB_USERNAME}
      DB_NAME: ${env:DB_NAME}
      DB_HOST: ${env:DB_HOST}
      DB_PORT: ${env:DB_PORT}
      SERVER_MODE: serverless

plugins:
  - serverless-offline
